### ISSUE TITLE
ChatManager附属报错

### ISSUE THREAD

**Issue by XiaoShuaiowo** [IllTamer/infinitebot4-expansion#12]
![error](https://github.com/IllTamer/infinite-bot-3-expansion/assets/63438522/dc61e708-5f86-47c2-97ed-a34c67406e68)
这是我的[config.yml](https://github.com/XiaoShuaiowo/XiaoShuai/blob/main/Temp/infinitebot3/expansions/ChatManager/config.yml)

**Comment by Thexiaoyuqaq** [comment]
聊天互通的有些问题待修复

**Comment by IllTamer** [comment]
新版附属（早）已解决（但是才推送更新）
